DELETE FROM `raw_pizzas` WHERE `title` = '1. FALUSI' AND `website_id` = '26';
DELETE FROM `raw_pizzas` WHERE `title` = '2. MAJDNEM VEGA' AND `website_id` = '26';
DELETE FROM `raw_pizzas` WHERE `title` = '3. FINCSI' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(paradicsommártás, szalámi, pepperóni, gomba, hagyma, sajt)' WHERE `title`='1. PEPPERÓNI' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(kapros fokhagymás-tejfölös alap, csirkemell csíkok, kukorica, sajt)' WHERE `title`='2. KAPROS' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(fokhagymás-tejfölös alap, gyrosos csirkemell csíkok, feta sajt, lila hagyma, sajt, paradicsom, oliva bogyó, oregano)' WHERE `title`='3. GYROS' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(tejszínes fokhagymás alap, sonka, garnéla, koktélparadicsom, sajt, bazsalikom)' WHERE `title`='4. GARNÉLARÁK' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(csípős paradicsommártás, füstölt tarja, kolbász, lilahagyma, füstölt sajt, sajt)' WHERE `title`='5. FÜSTÖS PIZZA' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(barbecue alap, sonka, fűszeres darált hús, lilahagyma, paprika, mozarella sajt, sajt)' WHERE `title`='6. BARBECUE' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(paradicsommártás, füstölt tarja, kolbász, szalámi, fűszeres darált hús, bacon, sajt)' WHERE `title`='1. VÁGÓHÍD' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(tejfölös alap, sonka, szalámi, csemege uborka, füstölt sajt, sajt)' WHERE `title`='8. UBORKÁS' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(paradicsommártás, sajt)' WHERE `title`='9. SAJTOS' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(3 szabadon választott feltét)' WHERE `title`='10. 3 KÍVÁNSÁG' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(paradicsommártás, sonka, gomba, sajt)' WHERE `title`='11. PAM-PAM' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(paradicsommártás, sonka, sajt)' WHERE `title`='12. SONKÁS' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(csípős paradicsomos alap, füstölt csülök, bab, sajt)' WHERE `title`='13. VADNYUGAT' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(paradicsommártás, sonka, gomba, ananász, kukorica, sajt)' WHERE `title`='14. 4 ÉVSZAK' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(paradicsomos alap, csülök, sonka, füstölt tarja, főtt tojás, bacon, sajt)' WHERE `title`='15. BRUTÁLIS' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(paradicsommártás, sonka, gomba, kolbász, kukorica, borsó, tükörtojás, sajt)' WHERE `title`='16. ÉHES EMBER PIZZÁJA' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(paradicsommártás, sonka, gomba, paprika, vöröshagyma, kolbász, sajt)' WHERE `title`='17. DOROZSMAI CSÍPŐS' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(paradicsommártás, sonka, lilahagyma, főtt tojás, bacon, sajt, tejfölös tormával meglocsolva)' WHERE `title`='18. HÚSVÉTI' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(csípős paradicsommártás alap, csülök, tarja, sonka, kolbász, bacon, paradicsom, hagyma, paprika, sajt, dupla tükörtojás)' WHERE `title`='19. CSAK KEMÉNYEKNEK' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(paradicsommártás, sonka, kukorica, sajt)' WHERE `title`='20. MEXIKÓI' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(paradicsommártás, gomba, borsó, kukorica, sajt)' WHERE `title`='21. VEGA' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(paradicsommártás, sonka, szardínia, kagyló, sajt)' WHERE `title`='22. FRUTTI DI MARI' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(paradicsommártás, füstölt sajt, trappista sajt, mozarella sajt, parmezán sajt)' WHERE `title`='23. NÉGY SAJTOS' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(paradicsommártás, füstölt tarja, kolbász, bacon, lilahagyma, fokhagyma, zöldpaprika, tojás, sajt)' WHERE `title`='24. NEHÉZFIÚ' AND `website_id` = '26';
UPDATE `raw_pizzas` SET `content`= '(csípős paradicsommártás, fűszeres darált hús, pepperóni, sonka sajt)' WHERE `title`='25. MAMUT' AND `website_id` = '26';
