INSERT INTO `raw_pizzas` ( `title`, `size`, `price`, `content`, `image`, `source_link`, `category_id`, `website_id`, `created_at`, `updated_at`) VALUES
('Crunch Smiley Sweet', '30', '1790', 'sajtkrémes alap, kolbász, szalámi, marinált paprika, dupla prémium sajtkeverék, paprikás stix chips', '', '', 3, 31, NULL, NULL),
('Crunch Smiley Hot', '30', '1790', 'csípős sajtkrémes alap, kolbász, szalámi, jalapeno, dupla prémium sajtkeverék, paprikás stix chips', '', '', 3, 31, NULL, NULL),
('Crunch Smokey Sweet', '30', '1790', 'füstölt sajtkrémes alap, bacon, csirke, marinált paprika, dupla prémium sajtkeverék, paprikás stix chips', '', '', 3, 31, NULL, NULL),
('Crunch Smokey Hot', '30', '1790', 'csípős füstölt sajtkrémes alap, bacon, csirke, jalapeno, dupla prémium sajtkeverék, paprikás stix chips', '', '', 3, 31, NULL, NULL),
('Crunch Sunny Sweet', '30', '1790', 'vörös cheddar sajtos alap, sonka, tarja, marinált paprika, dupla prémium sajtkeverék, paprikás stix chips', '', '', 3, 31, NULL, NULL),
('Crunch Sunny Hot', '30', '1790', ' csípős vörös cheddar sajtos alap, sonka, tarja, jalapeno, dupla prémium sajtkeverék, paprikás stix chips', '', '', 3, 31, NULL, NULL),
('CsK1 - csemege', '30', '1590', 'fokhagymás pizzaszósz, csabai házikolbász, TV paprika, sült hagyma, 3 féle sajt', '', '', 3, 31, NULL, NULL),
('CsK1 - csípős', '30', '1590', 'csípős pizzaszósz, csabai házikolbász, erős paprika, sült hagyma, 3 féle sajt', '', '', 3, 31, NULL, NULL),
('Chicagos Pizza Star', '26', '1590', 'cheddar sajtos alap, dupla adag prémium sajtkeverék, dupla pikáns kolbász, Heinz ketchup', '', '', 3, 31, NULL, NULL),
('New Yorks Pizza Star', '26', '1590', 'cheddar sajtos alap, dupla adag prémium sajtkeverék, pirított bacon, sült hagyma, Heinz ketchup', '', '', 3, 31, NULL, NULL),
('San Franciscos Pizza Star', '26', '1590', 'cheddar sajtos alap, dupla adag prémium sajtkeverék, grillcsirke, jalapeno, Heinz ketchup', '', '', 3, 31, NULL, NULL),
('Házias Magyaros', '30', '2190', 'töltött perem, tejfölös alap, prémium sonka, kolbász, lilahagyma, erős paprika, duplasajt', '', '', 3, 31, NULL, NULL),
('Made inItaly', '30', '2190', 'töltött perem, pizzaszósz, pármai sonka, paradicsom, pfefferóni, fekete oliva, dupla mozzarella', '', '', 3, 31, NULL, NULL),
('Pit BULL', '30', '2190', 'töltött perem, tejfölös alap, prémium sonka, bacon, virsli, tripla sajt', '', '', 3, 31, NULL, NULL),
('Pizza BUMM 3', '30', '2190', 'töltött perem, pizzaszósz, Pick szalámi, Pick kolbász, hagyma, kukorica, erős paprika, sajt', '', '', 3, 31, NULL, NULL),
('Pizza Speciale', '30', '2190', 'töltött perem, speciális alap, sonka, bacon, dupla sajt, dupla kaliforniai paprika', '', '', 3, 31, NULL, NULL),
('PizzaBURGER', '30', '2190', 'töltött perem, mustáros ketchupos alap, saláta, lilahagyma, hamburgerhús, csemegeuborka, paradicsom, sajt', '', '', 3, 31, NULL, NULL),
('PizzaBURGER 2 - Hot', '30', '2390', 'Burger szósz, saláta, hamburgerhús, pirított bacon, tükörtojás szeletek, lilahagyma, jelapeno paprika, lapka sajt, mozzarella, töltött perem', '', '', 3, 31, NULL, NULL),
('PizzaBURGER 2 - Sweet', '30', '2390', 'Burger szósz, saláta, hamburgergús, pirított bacon, tükörtojás szeletek, lila hagyma, csemege uborka, lapka sajt, mozzarella, töltött perem', '', '', 3, 31, NULL, NULL),
('Barbecue', '30', '1790', 'barbecues alap, grillcsirke, kaliforniai paprika, kukorica, sajt', '', '', 3, 31, NULL, NULL),
('Csemege', '30', '1790', 'pizzaszósz, csirke, prémium sonka, csemegeuborka, füstölt sajt', '', '', 3, 31, NULL, NULL),
('Kenyérlángos', '30', '1790', 'tejfölös alap, DUPLA pirított bacon, lila hagyma, sajt', '', '', 3, 31, NULL, NULL),
('Pizza di Parma', '30', '1790', 'italy pizzaszósz, Pármai sonka, paradicsom, sajt, parmesan', '', '', 3, 31, NULL, NULL),
('Pizza USA', '30', '1790', 'tejfölös alap, pirított bacon, virsli, DUPLA trappista sajt', '', '', 3, 31, NULL, NULL),
('Rubik TOP 1', '30', '1790', 'fokhagymás tejfölös alap, prémium sonka, bacon, kukorica, sajt', '', '', 3, 31, NULL, NULL),
('Pizza7 - Cheese', '30', '1990', 'Pizzaszósz, trappista, pannónia sajt, füstölt sajt, vörös cheddar sajt, márvány sajt, camambert, mozzarella', '', '', 3, 31, NULL, NULL),
('Pizza7 - Colour', '30', '1990', 'pizzaszósz, prémium sonka, bacon, csemege uborka, lila hagyma, kukorica, kaliforniai paprika, füstölt sajt, mozzarella', '', '', 3, 31, NULL, NULL),
('Pizza7 - Meat', '30', '1990', 'pizzaszósz, prémium sonka, bacon, tarja, csirke, kolbász, szalámi, virsli, mozzarella', '', '', 3, 31, NULL, NULL),
('Csibész Pizza', '30', '1790', 'tejf. alap, csirke, bacon, tarja, erős paprika, paradicsom, mozzarella', '', '', 3, 31, NULL, NULL),
('Full Ínyenc', '30', '1790', 'pizzaszósz, pármai sonka, paradicsom, fekete olivabogyó, camembert, parmesan, mozzarella', '', '', 3, 31, NULL, NULL),
('Füsti Pizza', '30', '1790', 'fokhagymás tejfölös alap, sonka, kolbász, szalámi, kukorica, csemegeuborka, füstölt sajt', '', '', 3, 31, NULL, NULL),
('Little BURGER Pizza', '30', '1790', 'burger szószos alap, saláta, hamburgerhús, csemegeuborka, lilahagyma, paradicsom, sajt', '', '', 3, 31, NULL, NULL),
('Mega Pizza', '30', '1790', 'pizzaszósz, Prémium sonka, bacon, Pick kolbász, hagyma, kukorica, mozzarella', '', '', 3, 31, NULL, NULL),
('Ötsajtos Pizza', '30', '1790', 'pizzaszósz, trappista, pannónia, füstölt sajt, márványsajt, parmesan, mozzarella', '', '', 3, 31, NULL, NULL),
('Pizza LEON', '30', '1790', 'vegyes borsos sajtkrémes alap, grill csirke, pirított bacon, sült hagyma, jalapeno paprika, márványsajt, sajt', '', '', 3, 31, NULL, NULL),
('Ragadozó Pizza', '30', '1790', 'pizzaszósz, pármai sonka, sonka, szalámi, bacon, dupla sajt', '', '', 3, 31, NULL, NULL),
('Vadász Pizza', '30', '1790', 'fokhagymás tejfölös alap, csirke, gomba, erős paprika, lila hagyma, márványsajt, mozzarella', '', '', 3, 31, NULL, NULL),
('Carbonara Pizza', '30', '1690', 'tejfölös alap, bacon, prémium sonka, kukorica, füstölt sajt, mozzarella\r\n', '', '', 3, 31, NULL, NULL),
('Füstölt Pizza', '30', '1690', 'fokh.tejf. alap, tarja, bacon, oliva, lila hagyma, füstölt karaván sajt', '', '', 3, 31, NULL, NULL),
('Húsos Pizza', '30', '1690', 'tejfölös alap, csirke, pick kolbász, bacon, dupla mozzarella', '', '', 3, 31, NULL, NULL),
('Magyaros Pizza', '30', '1690', 'pizzaszósz, bacon, Pick kolbász, hagyma, paprika, sajt', '', '', 3, 31, NULL, NULL),
('Mester Pizza', '30', '1690', 'pizzaszósz, prémium sonka, Pick szalámi, csemege uborka, füstölt sajt, mozzarella', '', '', 3, 31, NULL, NULL),
('Mr. Cheddar Pizza', '30', '1690', 'dijoni pizzaszósz, pirított bacon, sült hagyma, jalapeno paprika, vörös cheddar sajt, sajt', '', '', 3, 31, NULL, NULL),
('Pizza BUMM 2', '30', '1690', 'pizzaszósz, Pick szalámi, Pick kolbász, hagyma, kukorica, mozzarella', '', '', 3, 31, NULL, NULL),
('Pizza MZ/X', '30', '1690', 'csípős sajtkrémes alap, Pick szalámi, pfefferóni, feta, füstölt sajt, trappista sajt', '', '', 3, 31, NULL, NULL),
('Tüzes Pizza', '30', '1690', 'csípős szósz, Pick szalámi, bacon, lila hagyma, erős paprika, mozzarella', '', '', 3, 31, NULL, NULL),
('Bacon and Eggs Pizza', '30', '1590', 'majonézes tejfölös alap, pirított bacon, tükörtojás szeletek, lapka sajt, sajt', '', '', 3, 31, NULL, NULL),
('Bivaly Pizza', '30', '1590', 'tejfölös alap, sonka, erőspaprika, dupla trappista sajt', '', '', 3, 31, NULL, NULL),
('Bolognai Pizza', '30', '1590', 'pizzaszósz, bolognai ragu, bacon, parmesan, mozzarella\r\n', '', '', 3, 31, NULL, NULL),
('Hot-Dog Pizza', '30', '1590', 'mustáros-ketchupos alap, dupla virsli, sült hagyma, mozzarella\r\n', '', '', 3, 31, NULL, NULL),
('Húsfaló Pizza', '30', '1590', 'pizzaszósz, bacon, csirke, dupla sajt\r\n', '', '', 3, 31, NULL, NULL),
('Pármai Pizza', '30', '1590', 'pizzaszósz, pármai sonka, paradicsom, parmesan, mozzarella', '', '', 3, 31, NULL, NULL),
('PizzaGusto', '30', '1590', 'pizzaszósz, pármai sonka, paradicsom, ruccola, sajt', '', '', 3, 31, NULL, NULL),
('SGQ Pizza', '30', '1590', 'pizzaszósz, prémium sonka, gomba, kukorica, mozzarella', '', '', 3, 31, NULL, NULL),
('Tonhalas Pizza', '30', '1590', 'pizzaszósz, tonhal, oliva, hagyma, mozzarella', '', '', 3, 31, NULL, NULL),
('Csípős Pizza', '30', '1490', 'tejfölös alap, kolbász, erős paprika, trappista sajt', '', '', 3, 31, NULL, NULL),
('Falusi Pizza', '30', '1490', 'tejfölös alap, pirított bacon, lila hagyma, mozzarella', '', '', 3, 31, NULL, NULL),
('Fincsi Pizza', '30', '1490', 'pizzaszósz, csirke, csemege uborka, füstölt sajt', '', '', 3, 31, NULL, NULL),
('Hawaii Pizza', '30', '1490', 'pizzaszósz, prémium sonka, ananász, mozzarella', '', '', 3, 31, NULL, NULL),
('Hot Cheese Pizza', '30', '1490', 'sajtkrémes alap, pirított bacon, jalapeno paprika, sajt', '', '', 3, 31, NULL, NULL),
('Husi Pizza', '30', '1490', 'tejfölös alap, kolbász, pirított bacon, sajt', '', '', 3, 31, NULL, NULL),
('Pizza BUMM', '30', '1490', 'pizzaszósz, Pick kolbász, Pick szalámi, mozzarella', '', '', 3, 31, NULL, NULL),
('Sonkás Pizza', '30', '1490', 'pizzaszósz, prémium sonka, dupla mozzarella', '', '', 3, 31, NULL, NULL),
('SQ Pizza', '30', '1490', 'pizzaszósz, prémium sonka, kukorica, mozzarella', '', '', 3, 31, NULL, NULL);
