REPLACE INTO `links` (`id`, `url`, `main_filter_selector`, `website_id`, `category_id`, `item_schema_id`, `created_at`, `updated_at`) VALUES
(1, 'http://www.handballworld.szakdolgozat.net/shop?category=mez', '.col-lg-9 .row .col-lg-4', 1, 1, 1, NOW(), NOW()),
(3, 'http://www.pizzaguru.hu/etlap', '.page_bg_top table tbody tr td form table tbody', 3, 3, 3, NOW(), NOW()),
(4, 'http://www.gorogpizzeria.hu/etlap', '.page_bg_top table tbody tr td form table tbody', 4, 3, 4, NOW(), NOW()),
(5, 'http://pizza-pasta.hu/etlap/', '#td-block-748-13 div .wprm_single_menu_item', 5, 3, 5, NOW(), NOW()),
(7, 'https://american-chicken.hu/termekkategoria/pizza/', '.products .product-type-simple', 8, 3, 8, NOW(), NOW()),
(8, 'https://american-chicken.hu/termekkategoria/premium-pizzak/', '.products .product-type-simple', 8, 3, 8, NOW(), NOW()),
(9, 'http://www.hobiart.hu/kategoriak/pizzak', '.view-content .views-row', 9, 3, 10, NOW(), NOW()),
(10, 'https://www.lesdegesz.hu/home/kategoria/2/pizzak', '#product_list .browse_item .browse_lesdegesz table tr', 10, 3, 11, NOW(), NOW()),
(11, 'http://luckypizzeria.hu/pizza', '#main .container .row:nth-child(2) .col-lg-3 .product', 11, 3, 12, NOW(), NOW()),
(21, 'https://new.pizzamonster.hu/pizzak/', '#content .wf-container div article .woocom-project', 15, 3, 16, NOW(), NOW()),
(22, 'https://www.pizzatoronyszeged.hu/webshop/Pizza_30_cm', '.container section .col-md-6 .product_box', 16, 3, 17, NOW(), NOW()),
(23, 'https://rusticapizza.hu/etlap', '#category_2 .food-container .food', 17, 3, 18, NOW(), NOW()),
(24, 'https://rusticapizza.hu/etlap', '#category_43 .food-container .food', 17, 3, 18, NOW(), NOW()),
(25, 'https://turbopizza.hu/menu/pizzak-32-cm', '#content div.row:nth-child(6) .product-layout .product-thumb', 18, 3, 19, NOW(), NOW()),
(26, 'https://zedslice.hu/etlap', '#category_30 .food-container .food', 19, 5, 20, NOW(), NOW()),
(27, 'https://www.dqpizza.hu/pizza/', '.products .product .product-outer .product-inner .product-content-wrapper', 20, 3, 21, NOW(), NOW()),
(28, 'https://margaretapizza.hu/pizza-fajtak-90', '#snapshot_vertical .product-snapshot .snapshot_vertical_product', 21, 3, 22, NOW(), NOW()),
(29, 'https://margaretapizza.hu/pizza-fajtak-90?page=2#content', '#snapshot_vertical .product-snapshot .snapshot_vertical_product', 21, 3, 22, NOW(), NOW()),
(30, 'https://margaretapizza.hu/pizza-fajtak-90?page=3#content', '#snapshot_vertical .product-snapshot .snapshot_vertical_product', 21, 3, 22, NOW(), NOW()),
(31, 'https://www.bellaitalia.hu/index.php?p=chooseEtlap&chCat=3', '.infopage_no table table:nth-child(5) tr:nth-child(even)', 22, 3, 23, NOW(), NOW()),
(32, 'http://pizzakiraly.hu/index.php?route=product/category&path=59_68', '#mfilter-content-container .product-layout .product-thumb', 23, 3, 24, NOW(), NOW()),
(33, 'http://pizzakiraly.hu/index.php?route=product/category&path=70', '#mfilter-content-container .product-layout .product-thumb', 23, 3, 24, NOW(), NOW()),
(34, 'http://pizzakiraly.hu/index.php?route=product/category&path=69', '#mfilter-content-container .product-layout .product-thumb', 23, 3, 24, NOW(), NOW()),
(35, 'http://pizzakiraly.hu/index.php?route=product/category&path=71', '#mfilter-content-container .product-layout .product-thumb', 23, 3, 24, NOW(), NOW()),
(36, 'http://www.la-rosa.hu/szeged/termekkategoria/pizzak/', '.products li', 25, 3, 25, NOW(), NOW()),
(37, 'http://banyaicukraszda.hu/pizza/', '.arlista tr:nth-child(odd)', 26, 3, 26, NOW(), NOW()),
(38, 'http://www.trojaszeged.hu/etlap/pizzak', '.lista_elem tr', 27, 3, 27, NOW(), NOW()),
(39, 'https://pizzaforte.hu/pizzak.php', '#pizzak_list_1 tr td .product_info_panel', 28, 3, 28, NOW(), NOW());