INSERT INTO `raw_pizzas` (`title`, `size`, `price`, `content`, `image`, `source_link`, `category_id`, `website_id`, `created_at`, `updated_at`) VALUES
('SAJTOS', '30', '990', 'Paradicsomos alap, sajt', '', '', 3, 30, NULL, NULL),
('KUKORICA', '30', '1190', 'Paradicsomos alap, kukorica, sajt', '', '', 3, 30, NULL, NULL),
('SONKA', '30', '1190', 'Paradicsomos alap, sonka, sajt', '', '', 3, 30, NULL, NULL),
('GOMBÁS', '30', '1190', 'Paradicsomos alap, gomba, sajt', '', '', 3, 30, NULL, NULL),
('KOLBÁSZOS', '30', '1290', 'Paradicsomos alap, kolbász, sajt', '', '', 3, 30, NULL, NULL),
('SZALÁMIS', '30', '1390', 'Paradicsomos alap, szalámi, sajt', '', '', 3, 30, NULL, NULL),
('BACONOS', '30', '1390', 'Paradicsomos alap, bacon, sajt', '', '', 3, 30, NULL, NULL),
('TARJÁS', '30', '1390', 'Paradicsomos alap, tarja sajt', '', '', 3, 30, NULL, NULL),
('SONKA-KUKORICA', '30', '1390', 'Paradicsomos alap,sonka, kukorica, sajt', '', '', 3, 30, NULL, NULL),
('SONKA-GOMBA', '30', '1390', 'Paradicsomos alap, sonka, gomba, sajt', '', '', 3, 30, NULL, NULL),
('BOLOGNAI', '30', '1390', 'Paradicsomos alap, bolognai szósz,darált hús, sajt', '', '', 3, 30, NULL, NULL),
('CSÍPŐS', '30', '1490', 'Csípős alap, kolbász, csípős pfefferoni,  sajt', '', '', 3, 30, NULL, NULL),
('MÉRGES', '30', '1490', 'Csípős alap, sonka, csípős pfefferoni,  sajt', '', '', 3, 30, NULL, NULL),
('KOLBÁSZ-KUKORICA', '30', '1490', 'Paradicsomos alap, kolbász, kukorica, sajt', '', '', 3, 30, NULL, NULL),
('SZALÁMI-KUKORICA', '30', '1490', 'Paradicsomos alap, szalámi, kukorica, sajt', '', '', 3, 30, NULL, NULL),
('SZARDÍNIÁS', '30', '1490', 'Paradicsomos alap, szardínia, sajt', '', '', 3, 30, NULL, NULL),
('BABOS', '30', '1490', 'Csípős alap, sonka, chilis bab, sajt', '', '', 3, 30, NULL, NULL),
('NÉGY ÉVSZAK', '30', '1490', 'Paradicsomos alap, sonka, gomba, zöld borsó, kukorica, sajt', '', '', 3, 30, NULL, NULL),
('TANYA', '30', '1490', 'Tejfölös alap, tarja, hagyma, sajt', '', '', 3, 30, NULL, NULL),
('BBQ BACON', '30', '1490', 'BBQ alap, Bacon, hagyma, sajt', '', '', 3, 30, NULL, NULL),
('TONHALAS', '30', '1490', 'Paradicsomos alap, tonhal, sajt', '', '', 3, 30, NULL, NULL),
('SONKA-GOMBA-KUKORICA', '30', '1490', 'Paradicsomos alap, sonka, gomba, kukorica, sajt', '', '', 3, 30, NULL, NULL),
('HAWAI', '30', '1490', 'Paradicsomos alap, sonka, ananász, sajt', '', '', 3, 30, NULL, NULL),
('HAKAPESZI', '30', '1490', 'Paradicsomos alap, sonka, gomba, sajt, kapros tejfölös öntet', '', '', 3, 30, NULL, NULL),
('NUTELLÁS', '30', '1590', 'Nutella, földimogyoró', '', '', 3, 30, NULL, NULL),
('HARAGOS', '30', '1590', 'Csípős alap, szalámi, csípős pfefferoni,  sajt', '', '', 3, 30, NULL, NULL),
('SONKA-SZALÁMI', '30', '1590', 'Paradicsomos alap, sonka, szalámi, sajt', '', '', 3, 30, NULL, NULL),
('MEXIKÓI', '30', '1590', 'Csípős alap, bab, kukorica, sajt', '', '', 3, 30, NULL, NULL),
('MILÁNÓI', '30', '1590', 'Milánói alap, gomba, darálthús, sajt', '', '', 3, 30, NULL, NULL),
('TEJFÖLÖS TONHALAS', '30', '1590', 'Tejfölös alap, tonhal, hagyma, citrom, sajt', '', '', 3, 30, NULL, NULL),
('KAGYLÓS', '30', '1590', 'Paradicsomos alap, sonka, kagyló, sajt', '', '', 3, 30, NULL, NULL),
('RAY PIZZÁJA', '30', '1590', 'Paradicsomos alap, gépsonka, sajt, gorgonzola sajt', '', '', 3, 30, NULL, NULL),
('SZEZÁMOS', '30', '1590', 'Paradicsomos alap, 3 féle sajt, tetején tarja szeletek, szezámmaggal megszórva', '', '', 3, 30, NULL, NULL),
('\"BOCIS\" PIZZA', '30', '1690', 'Sajtkrémes alap, sonka, szalámi, sajt', '', '', 3, 30, NULL, NULL),
('FAVORIT', '30', '1690', 'Sajtkrémes alap, sonka, bacon, sajt', '', '', 3, 30, NULL, NULL),
('KENNY', '30', '1690', 'Sajtkrémes alap, szalámi, kukorica, sajt', '', '', 3, 30, NULL, NULL),
('FINCSI', '30', '1690', 'Fokhagymás tejfölös alap, tarja, kolbász, füstöltsajt, sajt', '', '', 3, 30, NULL, NULL),
('RÉMÁLOM', '30', '1690', 'Csípős alap, csípős kolbász, szalámi, jalapeno,  sajt', '', '', 3, 30, NULL, NULL),
('JUHTÚRÓS', '30', '1690', 'Tejfölös alap, juhtúró, pulykamellsonka, sajt, gorgonzola sajt', '', '', 3, 30, NULL, NULL),
('VIVI PIZZÁJA', '30', '1690', 'Paradicsomos alap, sonka,gomba,kukorica,lilahagyma, sajt', '', '', 3, 30, NULL, NULL),
('\"ZIDANE\"', '30', '1690', 'Sajtkrémes alap, csirke csíkok, sajt, füstölt sajt', '', '', 3, 30, NULL, NULL),
('MAGYAROS', '30', '1690', 'Paradicsomos alap, sonka, kolbász, tarja, hagyma, sajt', '', '', 3, 30, NULL, NULL),
('PARASZTOS', '30', '1690', 'Csípős alap, kolbász, Pick szalámi, hagyma,  erőspaprika, sajt', '', '', 3, 30, NULL, NULL),
('ÍNYENC', '30', '1690', 'Sajtkrémes alap, szalámi, sajt, tarja, lilahagyma', '', '', 3, 30, NULL, NULL),
('BETYÁROS', '30', '1690', 'Tejfölös alap, darált hús, kolbász, sajt, lilahagyma', '', '', 3, 30, NULL, NULL),
('OLIVÁS', '30', '1690', 'Paradicsomos alap, szalámi, gomba, olíva, kaliforniai paprika, sajt', '', '', 3, 30, NULL, NULL),
('GAMER', '30', '1690', 'Sajtkrémes alap, sonka, tarja, lilahagyma, sajt', '', '', 3, 30, NULL, NULL),
('NÉMÓ', '30', '1690', 'Tejfölös alap, sonka, tonhal, oliva, sajt', '', '', 3, 30, NULL, NULL),
('INDIAI', '30', '1690', 'Fűszeres paradicsomos alap, csirkehús, curry', '', '', 3, 30, NULL, NULL),
('FETA-SAJTOS', '30', '1690', 'Tejfölös-majonézes alap, sonka, szalámi, feta sajt, sajt', '', '', 3, 30, NULL, NULL),
('GYROS', '30', '1690', 'Fokhagymás tejfölös alap, gyros hús, sajt', '', '', 3, 30, NULL, NULL),
('PIZZAFALÓ KEDVENCE', '30', '1690', 'Fokhagymás tejfölös alap, sonka, bacon, csemege ubi, sajt	', '', '', 3, 30, NULL, NULL),
('TARJA-FALJA', '30', '1690', 'Paradicsomos alap, sonka, Pick szalámi, a sajt tetejére színhús tarjaszeletek', '', '', 3, 30, NULL, NULL),
('ÖTSAJTOS', '30', '1690', 'Sajtkrémes alap, trapista sajt, füstölt sajt, camabert sajt, mozzarella, parmezán', '', '', 3, 30, NULL, NULL),
('ERŐS ZOLI', '30', '1690', 'Csípős alap, darált hús, kolbász, duplasajt, erőspaprika', '', '', 3, 30, NULL, NULL),
('HUJUJUJJ', '30', '1690', 'Sajtkémes alap, sonka, dupla sajt, jalapeno paprika', '', '', 3, 30, NULL, NULL),
('HÚSOS', '30', '1690', 'Fokhagymás tejfölös alap, darálthús, szalámi, hagyma, sajt', '', '', 3, 30, NULL, NULL),
('FODRÁSZ KEDVENCE', '30', '1690', 'Sajtkrémes alap, kolbász, kukorica, duplasajt', '', '', 3, 30, NULL, NULL),
('HORGÁSZ KEDVENCE', '30', '1690', 'Csípős alap, kolbász, Pick szalámi, tarja,  erőspaprika, sajt', '', '', 3, 30, NULL, NULL),
('ATI', '30', '1690', 'Csípős alap, kolbász, Pick szalámi, kukorica,  erőspaprika, sajt', '', '', 3, 30, NULL, NULL),
('FRODÓ', '30', '1790', 'Sajtkrémes alap, bacon, kolbász, hagyma, tv paprika, sajt', '', '', 3, 30, NULL, NULL),
('FIGARO', '30', '1790', 'Tejfölös bolognai mártás, duplasonka, kukorica, sajt', '', '', 3, 30, NULL, NULL),
('HŰHA!!', '30', '1790', 'Tejfölös alap, sonka, Pick szalámi, csemegeuborka, dupla sajt', '', '', 3, 30, NULL, NULL),
('DREAM', '30', '1790', 'Sajtkrémes alap, sonka, kukorica, kolbász, lilahagyma, sajt', '', '', 3, 30, NULL, NULL),
('TENGER GYÜMÖLCSEI \"FRUTTI DI MARE\"', '30', '1790', 'Paradicsomos alap, polip, rák, tintahal, kagyló, sajt', '', '', 3, 30, NULL, NULL),
('GARNÉLÁS', '30', '1790', 'Kapros tejfölös alap, garnéla rák, citrom, sajt', '', '', 3, 30, NULL, NULL),
('HÚSHEGY', '30', '1890', 'Paradicsomos alap, sonka, kolbász, szalámi, tarja, sajt', '', '', 3, 30, NULL, NULL),
('TEJFÖLÖS TENGERÉSZ', '30', '1890', 'Tejfölös alap, polip, rák, tintahal, kagyló, hagyma, citrom, sajt', '', '', 3, 30, NULL, NULL),
('HAMBURGERES', '30', '1890', 'Paradicsomos alap, 4 db hambihús, sajt, hagyma, csemege ubi', '', '', 3, 30, NULL, NULL),
('HOT-DOG-os', '30', '1890', 'Paradicsomos alap, 30dkg mini hotdog, sajt, pirított hagyma, ketchup, mustár, majonéz', '', '', 3, 30, NULL, NULL),
('BRATESZ PIZZÁJA', '30', '1890', 'Sajtkrémes alap, sonka, Pick szalámi, tarja, lilahagyma, csípős zöld paprika, sajt', '', '', 3, 30, NULL, NULL),
('ROLI BOMBA', '30', '1890', 'Csípős alap, sonka, kolbász, Pick szalámi, dupla sajt, tetejére tarja szeletek', '', '', 3, 30, NULL, NULL),
('Gyömbéres csirke', '30', '1690', 'Gyömbéres paradicsomos alap, csirkehús, sajt', '', '', 3, 30, NULL, NULL),
('Tojásos', '30', '1690', 'Paradicsomos alap, sonka, bacon, sajt, tetejére tükör tojás', '', '', 3, 30, NULL, NULL),
('Szecsuáni', '30', '1790', 'Édes-Savanyú alap, bambusz, csirkehús, sajt', '', '', 3, 30, NULL, NULL),
('Kínai', '30', '1790', 'Paradicsomos alap, szója szósz, csirkehús, gomba, hagyma, sajt', '', '', 3, 30, NULL, NULL),
('Nagy Fal', '30', '1790', 'Paradicsomos alap, szója szósz, sertés, csirkehús, sajt', '', '', 3, 30, NULL, NULL),
('Ham & Eggs', '30', '1590', 'Paradicsomos alap, sonka, sajt, tojás', '', '', 3, 30, NULL, NULL),
('Kukori', '30', '1690', 'Sajtkrémes alap, sonka, kukorica, tükörtojás', '', '', 3, 30, NULL, NULL),
('Kotkoda', '30', '1790', 'Sajtkrémes alap, sonka, bacon, kukorica, tükörtojás', '', '', 3, 30, NULL, NULL),
('Sokmagvas', '30', '1690', 'Paradicsomos alap, sonka trappista, mozzarella, magvak (tökmag, napraforgómag, lenmag, szezám) ', '', '', 3, 30, NULL, NULL),
('Fitnesz', '30', '2390', 'Szénhidrát csökkentett tészta, Paradicsomos alap, csirkehús, csökkentett kalóriájú sajt, magvak (tökmag, napraforgómag, lenmag, szezámmag)', '', '', 3, 30, NULL, NULL),
('Pörköltes', '30', '1990', 'Paradicsomos alap, pörkölt, sajt', '', '', 3, 30, NULL, NULL),
('Cézár', '30', '1990', 'Paradicsomos alap, csirkehús, paradicsom, kígyóuborka, lilahagyma, oliva, fetasajt, sajt', '', '', 3, 30, NULL, NULL),
('Chilisbabos', '30', '1690', 'Csípős paradicsomos alap, darált hús, bab, kukorica, sajt ', '', '', 3, 30, NULL, NULL),
('Camambert-sajtos ', '30', '1690', 'Sajtkrémes alap, sonka,  sajt, Camambert sajt', '', '', 3, 30, NULL, NULL);
