INSERT INTO `pizza_category` (`id`, `name`, `link`, `url`, `sorrend`, `created_at`, `updated_at`) VALUES
(1, 'Margaréta Pizzák', 'margareta', 'margareta.webp', 1, NULL, NULL),
(2, 'Szalámis Pizzák', 'szalamis', 'szalamis.webp', 2, NULL, NULL),
(3, 'Hawaii Pizzák', 'hawaii', 'hawaii.webp', 5, NULL, NULL),
(4, 'Sonkás Pizzák', 'sonkas', 'sonkas.webp', 3, NULL, NULL),
(5, 'Gombás Pizzák', 'gombas', 'gombas.webp', 4, NULL, NULL),
(6, 'Görög Pizzák', 'gorog', 'gorog.webp', 13, NULL, NULL),
(7, 'Gyrosos Pizzák', 'gyrosos', 'gyrosos.webp', 18, NULL, NULL),
(8, 'Tonhalas Pizzák', 'tonhalas', 'tonhalas.webp', 17, NULL, NULL),
(9, 'Tenger gyümölcsei Pizzák', 'tenger-gyumolcsei', 'tengergyumolcse.webp', 15, NULL, NULL),
(10, 'Pepperónis Pizzák', 'pepperonis', 'pepperonis.webp', 9, NULL, NULL),
(11, 'Magyaros Pizzák', 'magyaros', 'magyaros.webp', 11, NULL, NULL),
(12, 'Bolognai Pizzák', 'bolognai', 'bolognai.webp', 10, NULL, NULL),
(13, 'Kukoricás Pizzák', 'kukoricas', 'kukoricas.webp', 6, NULL, NULL),
(14, 'Vegán Pizzák', 'vegan', 'vegan.webp', 14, NULL, NULL),
(15, 'Négy Évszak Pizzák', 'negy-evszak', 'negyevszak.webp', 12, NULL, NULL),
(16, 'BBQ Pizzák', 'bbq', 'bbq.webp', 16, NULL, NULL),
(17, 'Húsimádó Pizzák', 'husimado', 'husimado.webp', 8, NULL, NULL),
(18, 'Baconos Pizzák', 'baconos', 'baconos.webp', 7, NULL, NULL),
(19, 'Tojásos Pizzák', 'tojasos', 'tojasos.webp', 19, NULL, NULL);
