test:
  services:
    - "postgres:${POSTGRES_VERSION}"
  variables:
    POSTGRES_DB: test
  stage: test
  image: gliderlabs/herokuish:latest
  script:
    - vendor/bin/phpunit
  only:
    - branches
    - tags
  except:
    variables:
      - $TEST_DISABLED
